// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/install.ts";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/Hero.tsx";
import * as $$2 from "./islands/Nav.tsx";
import * as $$3 from "./islands/Navigation.tsx";
import * as $$4 from "./islands/Search.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/index.tsx": $2,
    "./routes/install.ts": $3,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/Hero.tsx": $$1,
    "./islands/Nav.tsx": $$2,
    "./islands/Navigation.tsx": $$3,
    "./islands/Search.tsx": $$4,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
